# Generated by Django 2.0.4 on 2018-04-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_question_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_sign',
        ),
    ]
